# Generated by Django 2.2.19 on 2021-06-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0002_auto_20210410_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='author',
            field=models.CharField(default='', max_length=255, verbose_name='account.Account'),
        ),
    ]
