# Generated by Django 2.2.19 on 2021-06-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0004_auto_20210604_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='description',
            field=models.CharField(default='ok', max_length=255),
        ),
    ]
