# Generated by Django 2.2.19 on 2021-06-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0005_publicchatroom_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
